services:
  web:
    build: .
    container_name: django_web
    command: >
     sh -c "python app/manage.py migrate --noinput && gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    env_file: .env
    volumes:
      - static_volume:/static
    depends_on:
      - db
      - redis  
    restart: always    


  db:
    image: postgres:14
    container_name: django_db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: django_redis
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: django_celery_worker
    command: celery -A app worker -l info
    env_file: .env
    depends_on:
      - web
      - redis
      - db

  celery_beat:
    build: .
    container_name: django_celery_beat
    command: celery -A beat -l info
    env_file: .env
    depends_on:
      - web
      - redis
      - db


  nginx:
    image: nginx:latest
    container_name: django_nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/static
      - ./nginx/nginx.conf:/etc/ngnix/conf.d/default.conf:ro
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: 
